<?php

namespace Gentor\Etsy\Facades;

use Illuminate\Support\Facades\Facade;

/**
 * Class Etsy
 * @package Gentor\Etsy\Facades
 *
 * All methods has only one argument, an array with two items (both are optional, depends on the method):
 * array('params' => array(), 'data' => array())
 * :params for uri params
 * :data for "post fields"
 *
 * @see https://www.etsy.com/developers/documentation
 *
 * @method static array getMethodTable(array $argument = [])
 * @method static array getPublicBaseline(array $argument = [])
 * @method static array getCategory(array $argument = [])
 * @method static array getSubCategory(array $argument = [])
 * @method static array getSubSubCategory(array $argument = [])
 * @method static array findAllCountry(array $argument = [])
 * @method static array getCountry(array $argument = [])
 * @method static array findByIsoCode(array $argument = [])
 * @method static array findAllFeaturedTreasuries(array $argument = [])
 * @method static array getFeaturedTreasuryById(array $argument = [])
 * @method static array findAllListingsForFeaturedTreasuryId(array $argument = [])
 * @method static array findAllActiveListingsForFeaturedTreasuryId(array $argument = [])
 * @method static array findAllFeaturedListings(array $argument = [])
 * @method static array findAllCurrentFeaturedListings(array $argument = [])
 * @method static array findAllFeaturedTreasuriesByOwner(array $argument = [])
 * @method static array getGuest(array $argument = [])
 * @method static array findAllGuestCarts(array $argument = [])
 * @method static array addToGuestCart(array $argument = [])
 * @method static array updateGuestCartListingQuantity(array $argument = [])
 * @method static array removeGuestCartListing(array $argument = [])
 * @method static array findGuestCart(array $argument = [])
 * @method static array updateGuestCart(array $argument = [])
 * @method static array deleteGuestCart(array $argument = [])
 * @method static array claimGuest(array $argument = [])
 * @method static array mergeGuest(array $argument = [])
 * @method static array generateGuest(array $argument = [])
 * @method static array listImageTypes(array $argument = [])
 * @method static array createListing(array $argument = [])
 * @method static array getListing(array $argument = [])
 * @method static array updateListing(array $argument = [])
 * @method static array deleteListing(array $argument = [])
 * @method static array getAttributes(array $argument = [])
 * @method static array getAttribute(array $argument = [])
 * @method static array updateAttribute(array $argument = [])
 * @method static array deleteAttribute(array $argument = [])
 * @method static array findAllListingFavoredBy(array $argument = [])
 * @method static array findAllListingFiles(array $argument = [])
 * @method static array uploadListingFile(array $argument = [])
 * @method static array findListingFile(array $argument = [])
 * @method static array deleteListingFile(array $argument = [])
 * @method static array findAllListingFundOnEtsyCampaign(array $argument = [])
 * @method static array findAllListingImages(array $argument = [])
 * @method static array uploadListingImage(array $argument = [])
 * @method static array getImage_Listing(array $argument = [])
 * @method static array deleteListingImage(array $argument = [])
 * @method static array getInventory(array $argument = [])
 * @method static array updateInventory(array $argument = [])
 * @method static array getProduct(array $argument = [])
 * @method static array getOffering(array $argument = [])
 * @method static array findAllListingShippingProfileEntries(array $argument = [])
 * @method static array createShippingInfo(array $argument = [])
 * @method static array getListingShippingUpgrades(array $argument = [])
 * @method static array createListingShippingUpgrade(array $argument = [])
 * @method static array updateListingShippingUpgrade(array $argument = [])
 * @method static array deleteListingShippingUpgrade(array $argument = [])
 * @method static array findAllListingTransactions(array $argument = [])
 * @method static array getListingTranslation(array $argument = [])
 * @method static array createListingTranslation(array $argument = [])
 * @method static array updateListingTranslation(array $argument = [])
 * @method static array deleteListingTranslation(array $argument = [])
 * @method static array getListingVariations(array $argument = [])
 * @method static array createListingVariations(array $argument = [])
 * @method static array updateListingVariations(array $argument = [])
 * @method static array createListingVariation(array $argument = [])
 * @method static array updateListingVariation(array $argument = [])
 * @method static array deleteListingVariation(array $argument = [])
 * @method static array findAllListingActive(array $argument = [])
 * @method static array getInterestingListings(array $argument = [])
 * @method static array getTrendingListings(array $argument = [])
 * @method static array pagesSignup(array $argument = [])
 * @method static array findPage(array $argument = [])
 * @method static array updatePageData(array $argument = [])
 * @method static array uploadAvatar(array $argument = [])
 * @method static array findAllPageCollections(array $argument = [])
 * @method static array createPageCollection(array $argument = [])
 * @method static array getPageCollection(array $argument = [])
 * @method static array updatePageCollection(array $argument = [])
 * @method static array deletePageCollection(array $argument = [])
 * @method static array getCollectionListings(array $argument = [])
 * @method static array addListingToCollection(array $argument = [])
 * @method static array removeListingFromCollection(array $argument = [])
 * @method static array findPageCollectionsForListings(array $argument = [])
 * @method static array addCurator(array $argument = [])
 * @method static array removeCurator(array $argument = [])
 * @method static array curatorPeopleSearch(array $argument = [])
 * @method static array findPayment(array $argument = [])
 * @method static array findPaymentAdjustments(array $argument = [])
 * @method static array findPaymentAdjustment(array $argument = [])
 * @method static array findPaymentAdjustmentItem(array $argument = [])
 * @method static array getPrivateBaseline(array $argument = [])
 * @method static array getPropertyOptionModifier(array $argument = [])
 * @method static array findAllSuggestedPropertyOptions(array $argument = [])
 * @method static array findPropertySet(array $argument = [])
 * @method static array getShop_Receipt2(array $argument = [])
 * @method static array updateReceipt(array $argument = [])
 * @method static array findAllReceiptListings(array $argument = [])
 * @method static array findAllShop_Receipt2Transactions(array $argument = [])
 * @method static array findAllRegion(array $argument = [])
 * @method static array getRegion(array $argument = [])
 * @method static array findEligibleRegions(array $argument = [])
 * @method static array findBrowseSegments(array $argument = [])
 * @method static array findBrowseSegmentListings(array $argument = [])
 * @method static array findBrowseSegmentPosters(array $argument = [])
 * @method static array getServerEpoch(array $argument = [])
 * @method static array ping(array $argument = [])
 * @method static array getShippingCosts(array $argument = [])
 * @method static array getShippingInfo(array $argument = [])
 * @method static array updateShippingInfo(array $argument = [])
 * @method static array deleteShippingInfo(array $argument = [])
 * @method static array getPostageRates(array $argument = [])
 * @method static array createShippingTemplate(array $argument = [])
 * @method static array getShippingTemplate(array $argument = [])
 * @method static array updateShippingTemplate(array $argument = [])
 * @method static array deleteShippingTemplate(array $argument = [])
 * @method static array findAllShippingTemplateEntries(array $argument = [])
 * @method static array findAllShippingTemplateUpgrades(array $argument = [])
 * @method static array createShippingTemplateUpgrade(array $argument = [])
 * @method static array updateShippingTemplateUpgrade(array $argument = [])
 * @method static array deleteShippingTemplateUpgrade(array $argument = [])
 * @method static array createShippingTemplateEntry(array $argument = [])
 * @method static array getShippingTemplateEntry(array $argument = [])
 * @method static array updateShippingTemplateEntry(array $argument = [])
 * @method static array deleteShippingTemplateEntry(array $argument = [])
 * @method static array findAllShops(array $argument = [])
 * @method static array getShop(array $argument = [])
 * @method static array updateShop(array $argument = [])
 * @method static array getShopAbout(array $argument = [])
 * @method static array uploadShopBanner(array $argument = [])
 * @method static array deleteShopBanner(array $argument = [])
 * @method static array findAllShopCoupons(array $argument = [])
 * @method static array createCoupon(array $argument = [])
 * @method static array findCoupon(array $argument = [])
 * @method static array updateCoupon(array $argument = [])
 * @method static array deleteCoupon(array $argument = [])
 * @method static array findLedger(array $argument = [])
 * @method static array findLedgerEntries(array $argument = [])
 * @method static array findLedgerEntry(array $argument = [])
 * @method static array findPaymentAdjustmentForLedgerEntry(array $argument = [])
 * @method static array findPaymentForLedgerEntry(array $argument = [])
 * @method static array findAllShopListingsActive(array $argument = [])
 * @method static array findAllShopListingsDraft(array $argument = [])
 * @method static array findAllShopListingsExpired(array $argument = [])
 * @method static array getShopListingExpired(array $argument = [])
 * @method static array findAllShopListingsFeatured(array $argument = [])
 * @method static array findAllShopListingsInactive(array $argument = [])
 * @method static array getShopListingInactive(array $argument = [])
 * @method static array findShopPaymentTemplates(array $argument = [])
 * @method static array createShopPaymentTemplate(array $argument = [])
 * @method static array updateShopPaymentTemplate(array $argument = [])
 * @method static array findAllShopReceipts(array $argument = [])
 * @method static array findShopPaymentByReceipt(array $argument = [])
 * @method static array submitTracking(array $argument = [])
 * @method static array findAllShopReceiptsByStatus(array $argument = [])
 * @method static array findAllOpenLocalDeliveryReceipts(array $argument = [])
 * @method static array searchAllShopReceipts(array $argument = [])
 * @method static array getShopReviews(array $argument = [])
 * @method static array findAllShopSections(array $argument = [])
 * @method static array createShopSection(array $argument = [])
 * @method static array getShopSection(array $argument = [])
 * @method static array updateShopSection(array $argument = [])
 * @method static array deleteShopSection(array $argument = [])
 * @method static array findAllShopSectionListings(array $argument = [])
 * @method static array findAllShopSectionListingsActive(array $argument = [])
 * @method static array getShopSectionTranslation(array $argument = [])
 * @method static array createShopSectionTranslation(array $argument = [])
 * @method static array updateShopSectionTranslation(array $argument = [])
 * @method static array deleteShopSectionTranslation(array $argument = [])
 * @method static array findAllShopTransactions(array $argument = [])
 * @method static array getShopTranslation(array $argument = [])
 * @method static array createShopTranslation(array $argument = [])
 * @method static array updateShopTranslation(array $argument = [])
 * @method static array deleteShopTranslation(array $argument = [])
 * @method static array getListingShop(array $argument = [])
 * @method static array getBuyerTaxonomy(array $argument = [])
 * @method static array findAllTopCategory(array $argument = [])
 * @method static array findAllTopCategoryChildren(array $argument = [])
 * @method static array findAllSubCategoryChildren(array $argument = [])
 * @method static array getTaxonomyNodeProperties(array $argument = [])
 * @method static array getSellerTaxonomy(array $argument = [])
 * @method static array getSellerTaxonomyVersion(array $argument = [])
 * @method static array findSuggestedStyles(array $argument = [])
 * @method static array findAllTeams(array $argument = [])
 * @method static array findAllUsersForTeam(array $argument = [])
 * @method static array findTeams(array $argument = [])
 * @method static array getShop_Transaction(array $argument = [])
 * @method static array findAllTreasuries(array $argument = [])
 * @method static array getTreasury(array $argument = [])
 * @method static array deleteTreasury(array $argument = [])
 * @method static array findTreasuryComments(array $argument = [])
 * @method static array postTreasuryComment(array $argument = [])
 * @method static array deleteTreasuryComment(array $argument = [])
 * @method static array addTreasuryListing(array $argument = [])
 * @method static array removeTreasuryListing(array $argument = [])
 * @method static array describeOccasionEnum(array $argument = [])
 * @method static array describeRecipientEnum(array $argument = [])
 * @method static array describeWhenMadeEnum(array $argument = [])
 * @method static array describeWhoMadeEnum(array $argument = [])
 * @method static array findAllUsers(array $argument = [])
 * @method static array getUser(array $argument = [])
 * @method static array findAllUserAddresses(array $argument = [])
 * @method static array createUserAddress(array $argument = [])
 * @method static array getUserAddress(array $argument = [])
 * @method static array deleteUserAddress(array $argument = [])
 * @method static array getAvatarImgSrc(array $argument = [])
 * @method static array getUserBillingOverview(array $argument = [])
 * @method static array getAllUserCarts(array $argument = [])
 * @method static array addToCart(array $argument = [])
 * @method static array updateCartListingQuantity(array $argument = [])
 * @method static array removeCartListing(array $argument = [])
 * @method static array getUserCart(array $argument = [])
 * @method static array updateCart(array $argument = [])
 * @method static array deleteCart(array $argument = [])
 * @method static array addAndSelectShippingForApplePay(array $argument = [])
 * @method static array findAllCartListings(array $argument = [])
 * @method static array saveListingForLater(array $argument = [])
 * @method static array getUserCartForShop(array $argument = [])
 * @method static array createSingleListingCart(array $argument = [])
 * @method static array findAllUserCharges(array $argument = [])
 * @method static array getUserChargesMetadata(array $argument = [])
 * @method static array getCirclesContainingUser(array $argument = [])
 * @method static array getConnectedUser(array $argument = [])
 * @method static array unconnectUsers(array $argument = [])
 * @method static array listFollowingPages(array $argument = [])
 * @method static array followPage(array $argument = [])
 * @method static array unfollowPage(array $argument = [])
 * @method static array getConnectedUsers(array $argument = [])
 * @method static array connectUsers(array $argument = [])
 * @method static array findAllUserFavoredBy(array $argument = [])
 * @method static array findAllUserFavoriteListings(array $argument = [])
 * @method static array findUserFavoriteListings(array $argument = [])
 * @method static array createUserFavoriteListings(array $argument = [])
 * @method static array deleteUserFavoriteListings(array $argument = [])
 * @method static array findAllUserFavoriteUsers(array $argument = [])
 * @method static array findUserFavoriteUsers(array $argument = [])
 * @method static array createUserFavoriteUsers(array $argument = [])
 * @method static array deleteUserFavoriteUsers(array $argument = [])
 * @method static array findAllUserFeedbackAsAuthor(array $argument = [])
 * @method static array findAllUserFeedbackAsBuyer(array $argument = [])
 * @method static array findAllUserFeedbackAsSeller(array $argument = [])
 * @method static array findAllUserFeedbackAsSubject(array $argument = [])
 * @method static array findAllFeedbackFromBuyers(array $argument = [])
 * @method static array findAllFeedbackFromSellers(array $argument = [])
 * @method static array findAllUserPayments(array $argument = [])
 * @method static array findAllUserPaymentTemplates(array $argument = [])
 * @method static array findUserProfile(array $argument = [])
 * @method static array updateUserProfile(array $argument = [])
 * @method static array findAllUserBuyerReceipts(array $argument = [])
 * @method static array findAllUserShippingProfiles(array $argument = [])
 * @method static array findAllUserShops(array $argument = [])
 * @method static array findAllTeamsForUser(array $argument = [])
 * @method static array findAllUserBuyerTransactions(array $argument = [])
 * @method static array findAllUserTreasuries(array $argument = [])
 */
class Etsy extends Facade
{
    /**
     * Get the registered name of the component.
     *
     * @return string
     */
    protected static function getFacadeAccessor()
    {
        return 'etsy';
    }
}